### ISSUE TITLE
How to - Blackcoin 1.2.4 for linux 

### ISSUE THREAD

**Issue by ZerooCool** [CoinBlack/blackcoin#10]
usertest@debian-8:~/blackcoin-1.2.4-linux$ ./blackcoin-qt

./blackcoin-qt: /usr/lib/x86_64-linux-gnu/libQt5Network.so.5: no version information available (required by ./blackcoin-qt)
./blackcoin-qt: /usr/lib/x86_64-linux-gnu/libQt5DBus.so.5: no version information available (required by ./blackcoin-qt)
./blackcoin-qt: /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5: no version information available (required by ./blackcoin-qt)
./blackcoin-qt: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: no version information available (required by ./blackcoin-qt)
./blackcoin-qt: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: no version information available (required by ./blackcoin-qt)
./blackcoin-qt: /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5: no version information available (required by ./blackcoin-qt)
./blackcoin-qt: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by ./blackcoin-qt)
./blackcoin-qt: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ./blackcoin-qt)

How to launch blackcoin-qt ?

**Comment by ghost** [comment]
It requires newer system libraries.

**Comment by ZerooCool** [comment]
where i can found ?
