### ISSUE TITLE
i reported an exception,when i create a transaction and write OP_RETURN to this transaction , please help me.

### ISSUE THREAD

**Issue by axing1991** [CoinBlack/blackcoin#11]
throw JSONRPCError(RPC_DESERIALIZATION_ERROR, "TX decode failed");
![image](https://user-images.githubusercontent.com/12743125/31325961-565f64ae-ac88-11e7-9364-1802bc1e80ae.png)

**Comment by janko33bd** [comment]
Can you please post the raw tx in text not in picture!

**Comment by michelvankessel** [comment]
closing old legacy wallet v1.2.x issues 

please migrate to Blackcoin More and download it from https://blackcoinmore.org
New issues can be posted on Gitlab: https://gitlab.com/blackcoin/blackcoin-more/-/issues
