### ISSUE TITLE
QT-Wallet 1.2.4. - issue for first import of a private key.

### ISSUE THREAD

**Issue by awachtler** [CoinBlack/blackcoin#13]
I use BlackCoin QT Wallet 1.2.4, pulled yesterday from this repo, running under Ubuntu 16.04.

I created a "fake" private key with VersionByte 153. 
`importprivkey 69frDvS2QNSjiaQYQY1hfgeh7hjohuJN29QqRfPuyDKeUDJgiKt MY_KEY_A5`

The key is accepted in terminal, after few seconds the main window gets unresponsive, after minutes or so, the main window gets responsive again but MY_KEY_A5 does not make it to the list of my BlackCoin-Addresses.

If I repeat the command from above, then everything runs quickly, no unresponsiveness for the second time and MY_KEY_A5 appears in the main window.

Here is the program, I've used to generate the key material:

    import hashlib
    import base58
    def encodeWif(secretString, versionByte = 0x80):
        bin_key = [ chr(int(secretString[l:l+2], 16)) for l in range(0, len(secretString), 2)]
        str_key = "".join(bin_key)	
        # extkey, secret prefixed by version byte
        ext_key = chr(versionByte) + str_key
        # double hash the ext_key
        d1 = hashlib.sha256(ext_key).digest()
        d2 = hashlib.sha256(d1).digest()
        secret_key = ext_key + "".join(map(chr,map(ord,d2[:4])))	
        priv_key = base58.b58encode(secret_key)
        return priv_key

    BLK_VERSION_BYTE_SEC_KEY = 153
    #raw_key = "0C28FCA386C7A227600B2FE50B7CAE11EC86D3BF1FBE471BE89827E19D72AA1D"
    #raw_key = "834298650AC8639E075680BBB2D0DC7CFABBC91E85A977D9ECD9C8881FBFE809"
    raw_key = "A5"*32
    print BLK_VERSION_BYTE_SEC_KEY, encodeWif(raw_key, BLK_VERSION_BYTE_SEC_KEY)

**Comment by michelvankessel** [comment]
closing old legacy wallet v1.2.x issues 

please migrate to Blackcoin More and download it from https://blackcoinmore.org
New issues can be posted on Gitlab: https://gitlab.com/blackcoin/blackcoin-more/-/issues
