### ISSUE TITLE
New Add

### ISSUE THREAD

**Issue by godexdev** [CoinBlack/blackcoin#15]
Hello!
Can you please add Godex to your "Where to buy" list?
https://godex.io
Thanks in advance!

**Comment by janko33bd** [comment]
wrong repository, please close this

**Comment by godexdev** [comment]
Can you please tell me which repository I need?

**Comment by janko33bd** [comment]
https://github.com/joshuajbouw/joshuajbouw.github.io

**Comment by godexdev** [comment]
Thank You!
