### ISSUE TITLE
AtomicPointer

### ISSUE THREAD

**Issue by Kuurusch** [CoinBlack/blackcoin#16]
Hallo, I've tried to install the newest version on a bananapi (Ubuntu) but I got the error: Please implement AtomicPointer for this platform. I've read, it's something with big-endian architecture. Is it so and is there a workaround?

Thanks a lot!

**Comment by michelvankessel** [comment]
closing old legacy wallet v1.2.x issues 

please migrate to Blackcoin More and download it from https://blackcoinmore.org
New issues can be posted on Gitlab: https://gitlab.com/blackcoin/blackcoin-more/-/issues
