### ISSUE TITLE
blackcoin mining the first block on testnet how?

### ISSUE THREAD

**Issue by openbooknoobdeveloper** [CoinBlack/blackcoin#17]
Hi all,  how can I mine the first block on testnet.

setgenerate true does not work thanks.

**Comment by janko33bd** [comment]
get on gitter, can help you there

**Comment by openbooknoobdeveloper** [comment]
Hi thanks janko33bd , can you provide the link? I can't find :(, thank you

**Comment by openbooknoobdeveloper** [comment]
hi @JohnDolittle i went to gitter and nobody could help me with this question, can you please reopen? thank you.

**Comment by ghost** [comment]
I'd rather not answer this as a major upgrade is in the works.
Alternatively, I can try to give some insight, if you describe what you want to test.

**Comment by michelvankessel** [comment]
there is a testnet. start blackcoin with the -testnet parameter. if you use the the latest version, you should autoconnect

**Comment by michelvankessel** [comment]
closing old legacy wallet v1.2.x issues 

please migrate to Blackcoin More and download it from https://blackcoinmore.org
New issues can be posted on Gitlab: https://gitlab.com/blackcoin/blackcoin-more/-/issues
