### ISSUE TITLE
Error Windows Wallet Compilation with QRCODE enabaling

### ISSUE THREAD

**Issue by dev12345601** [CoinBlack/blackcoin#18]
dedialog.o src/qt/qrcodedialog.cpp
src/qt/qrcodedialog.cpp:12:22: fatal error: qrencode.h: No such file or directory
compilation terminated.
Makefile.Release:94227: recipe for target 'build/qrcodedialog.o' failed

**Comment by michelvankessel** [comment]
closing old legacy wallet v1.2.x issues 

please migrate to Blackcoin More and download it from https://blackcoinmore.org
New issues can be posted on Gitlab: https://gitlab.com/blackcoin/blackcoin-more/-/issues
