### ISSUE TITLE
Build for v1.2.5 failing on Ubuntu 18.04

### ISSUE THREAD

**Issue by Curtingham** [CoinBlack/blackcoin#19]
Build of version 1.2.5 source code appears to be failing on Ubuntu 18.04.

I have a script to build blackcoind which fails on Ubuntu 18.04 with following error:
`makefile.unix:179: recipe for target 'obj/alert.o' failed`

Running the same exact script on Ubuntu 16.04 builds without any problem.

Contents of the script boil down to this (Other parts of the script just have to do with copying the executable to another location, etc.):
`cd /home/$(whoami)`
`git clone https://github.com/CoinBlack/blackcoin.git`
`cd /home/$(whoami)/blackcoin/src`
`make --jobs="$(nproc)" --makefile=makefile.unix USE_UPNP=- USE_QRCODE=0`

Happy to provide any additional info which may help identify the issue, just let me know.

**Comment by ghost** [comment]
Openssl 1.1 isn't supported.
Install libssl1.0-dev instead of libssl-dev
