### ISSUE TITLE
How to prevent the withdrawal of large currency may cause the main network to stop running risks

### ISSUE THREAD

**Issue by Nixiangyu** [CoinBlack/blackcoin#20]
Hello, I would like to ask, if a miner with a large amount of money left the main network, according to the consensus, the whole chain may stop running, because no miners have reached this target value, and only calculate a hash case, so how to deal with this situation, because the white paper does not explain this situation. For this, I want to know about it. Thank you very much.

**Comment by ghost** [comment]
It may take long time to find blocks, but difficulty will readjust eventually.

**Comment by Nixiangyu** [comment]
@JohnDolittle So how do we tell whether the main network is really out of block or broken? My understanding is that the block time is fixed, so beyond this block time to determine the current difficulty is too high, need to adjust the difficulty, or other ways to determine the current network status, then how to determine?
