### ISSUE TITLE
The alert message is disabling RPC APIs

### ISSUE THREAD

**Issue by joshuajbouw** [CoinBlack/blackcoin#23]
The alert message included in the latest update is disabling everyone's RPC APIs. Not the most stylish of issue reports I know.

**Comment by ghost** [comment]
Re-sent alert

**Comment by joshuajbouw** [comment]
The alert disabled every wallet in safemode it appears, so exchanges + CryptoID, noticed that latest update ignores the alert. Please please please tell me about this before you do this. I have to notify a long list of people.
