### ISSUE TITLE
txdb-leveldb.o issue on ubuntu 14.04

### ISSUE THREAD

**Issue by thinkblockchain** [CoinBlack/blackcoin#26]
when compiling i got this error:
``
**make: *** [build/txdb-leveldb.o] Error 1**

**Comment by joshuajbouw** [comment]
Hey there, please double check if your dependencies are correct. It's not the same as other blockchain projects.

Development has moved to Blackcoin More, which is a new software version of Blackcoin protocol. Once the first version is out, there will be more readily available support there. The new team has been working on that for release now.

**Comment by michelvankessel** [comment]
closing old legacy wallet v1.2.x issues 

please migrate to Blackcoin More and download it from https://blackcoinmore.org
New issues can be posted on Gitlab: https://gitlab.com/blackcoin/blackcoin-more/-/issues
