### ISSUE TITLE
inputs disappearing in watchonly branch

### ISSUE THREAD

**Issue by dzimbeck** [CoinBlack/blackcoin#3]
During staking the inputs in the watchonly branch have been disappearing and reappearing. There is a potential that this branch was not adjusted properly for reorganizations. I've tested exhaustively and seen the branch to not always return an accurate list of inputs. The problem usually corrects itself. However, the command listunspent does not always return the proper balance. Even after a rescan the balance has been wrong. Please investigate to see if the watchonly branch properly considers changes in the stake.

**Comment by michelvankessel** [comment]
closing old legacy wallet v1.2.x issues 

please migrate to Blackcoin More and download it from https://blackcoinmore.org
New issues can be posted on Gitlab: https://gitlab.com/blackcoin/blackcoin-more/-/issues
