### ISSUE TITLE
Testnet 

### ISSUE THREAD

**Issue by BlackFoxController** [CoinBlack/blackcoin#4]
Can we setup a testnet? Is there a chance we can skip checkpoints and is there a way to add testnet consensus rule(s) to generate coins to a testnet address (skip all proof of work and skip to v3 straight away)? Is there a way to have this testnet working / start from scratch on a new node/ pair? 

( Small reddit discussion: https://www.reddit.com/r/blackcoin/comments/6jh2a3/testnet/ )

**Comment by ghost** [comment]
It used to work. v3 is there from genesis block, but it requires some PoW to issue and mature coins. There's no checkpoints. Send me a list of nodes if you want to run the public testnet.
