### ISSUE TITLE
How to Debian stretch and blackcoin wallet

### ISSUE THREAD

**Issue by ZerooCool** [CoinBlack/blackcoin#7]
My install way :
https://www.visionduweb.eu/wiki/index.php?title=Conserver_son_portefeuille_sur_son_ordinateur_tablette_mobile#Installer_un_portefeuille_pour_la_cryptomonnaie_de_votre_choix

Can't make the compilation : error
https://www.visionduweb.eu/wiki/index.php?title=Erreurs_%C3%A0_la_compilation_du_portefeuille_Blackcoin

Visiblement c'est un problème avec OpenSSL qui serrait trop récent sur Stretch ?

**Comment by ghost** [comment]
Install `libssl1.0-dev` instead of `libssl-dev`

**Comment by ZerooCool** [comment]
Working good. Thank you !
https://www.visionduweb.eu

Tutorial up, in french, for Blackcoin wallet : 
https://www.visionduweb.eu/wiki/index.php?title=Conserver_son_portefeuille_sur_son_ordinateur_tablette_mobile#Installer_un_portefeuille_pour_la_cryptomonnaie_de_votre_choix
