### ISSUE TITLE
Official Github Blackcoin ?

### ISSUE THREAD

**Issue by ZerooCool** [CoinBlack/blackcoin#9]
Hello.
I'm looking for the latest version of the Blackcoin Wallet.

I found other sources about Blackcoin on Github. Is this the official portfolio of the Blackcoin community?

I wrote yesterday, about the installation of the Blackcoin wallet for Stretch, and, you have already been able to help me. Thank you. It works now.

In french : Tutoriel pour installer un portefeuille Blackcoin sur GNU/Linux.
https://www.visionduweb.eu/wiki/index.php?title=Conserver_son_portefeuille_sur_son_ordinateur_tablette_mobile#Installer_un_portefeuille_pour_la_cryptomonnaie_de_votre_choix

**Comment by janko33bd** [comment]
Your tutorial is wrong, it uses old wallet which is 3 years old, in these 3 years blackcoin has changed substantially..

**Comment by ZerooCool** [comment]
Ok but how i can found the good Wallet ? The good Github Link ?

I see this link from the official website. The link give Github and a take the first CoinBlack/blackcoin.

**Comment by janko33bd** [comment]
You have found the right wallet, staking tutorial on that link you have provided is old.

**Comment by ZerooCool** [comment]
But, my tutorial is good or not ?

**First : https://www.visionduweb.eu/wiki/index.php?title=Conserver_son_portefeuille_sur_son_ordinateur_tablette_mobile#Blackcoin_Wallet_pour_GNU.2FLinux**

OK.
Utiliser les paquets officiels : https://github.com/CoinBlack/blackcoin/releases

OK.
Télécharger : https://github.com/CoinBlack/blackcoin/archive/v1.2.4.tar.gz
Placer dans le root, puis, compiler avec qmake et make.
Blackcoin est installé. Blackcoin-qt fonctionne.
Résolu.

NOT OK. KO. Not working for me, how to ?
Télécharger le portefeuille en mode graphique depuis le lien suivant : https://github.com/CoinBlack/blackcoin/files/887665/blackcoin-1.2.4-linux.zip

How use the file .asc ?
Comment utiliser le fichier blackcoin-qt.asc ?

Second : https://www.visionduweb.eu/wiki/index.php?title=Conserver_son_portefeuille_sur_son_ordinateur_tablette_mobile#Installer_un_portefeuille_pour_la_cryptomonnaie_de_votre_choix

OK or NOT OK ?
This repository : git clone https://github.com/CoinBlack/blackcoin

OK or NOT ?
I don' have ./autogen.sh and ./configure 

Bibliographie - Sources - For my tutoriel:
Comment compiler un wallet qt : http://thecryptoworld.org/comment-compiler-un-wallet-qt-sous-ubuntu
Tutoriel proposé depuis Github qui m'a permis d'identifier les paquets a installer : https://github.com/CoinBlack/blackcoin/blob/master/doc/readme-qt.rst

Why friends say :  Your tutorial is wrong, it uses old wallet which is 3 years old, in these 3 years blackcoin has changed substantially. Why ? How to ?

**Comment by janko33bd** [comment]
Please move this conversation to bitcointalk, github code repository is not a good place. We can continue conversation here: https://bitcointalk.org/index.php?topic=469640
